services:
  viagens:
    image: 'bitnami/postgresql'
    container_name: shopper-viagens
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./db:/var/lib/postgresql
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DATABASE}
    networks:
      - shopper-nather
  server:
    build: 
      context: .
    ports:
      - "${PORT}:${PORT}"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_DATABASE}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?schema=public
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - shopper-nather
    depends_on:
      - viagens

volumes:
  db:

networks:
  shopper-nather:
    driver: bridge